### ISSUE TITLE
new spaces link

### ISSUE THREAD

**Issue by riccardito** [tamberg/fhnw-idb#3]
mir ist gerade aufgefallen, dass sich der idb space link im readme auf die alte ds-spaces seite verweist, was nicht mehr aktuell ist. 
liebe grüsse
Riccard

**Comment by tamberg** [comment]
Danke, fixed: https://github.com/tamberg/fhnw-idb/commit/38efd9d80f05f7663fd629ff821a97bdd4bae3b3
