### ISSUE TITLE
Wrong link on Grove-Sensors -> Ultrasonic Ranger

### ISSUE THREAD

**Issue by gabrieltorresgamez** [tamberg/fhnw-idb#4]
Link under
[https://github.com/tamberg/fhnw-idb/wiki/Grove-Sensors#circuitpython-7](https://github.com/tamberg/fhnw-idb/wiki/Grove-Sensors#circuitpython-7)
leads to a 404 Error page.

**Comment by tamberg** [comment]
The code to port is https://github.com/Seeed-Studio/grove.py/blob/master/grove/grove_ultrasonic_ranger.py

**Comment by tamberg** [comment]
Ported the Python example code to Circuitpython, see https://github.com/tamberg/fhnw-idb/tree/master/data-acquisition/CircuitPython/grove_ultrasonic_ranger
